--
-- Script was generated by Sushrut for EMRMS, Version 1.0.0.0
-- Script date 09/05/2017 21:52:44 PM
-- Server version: 5.7.19-log
--

-- Delete all data before inserting sample data
  
DELETE FROM h_person;
DELETE FROM h_name;
DELETE FROM h_patient;
DELETE FROM h_staff;
DELETE FROM h_bed;
DELETE FROM h_encounter;

-------------------------- INSERT INTO h_person--------------------------------------------------

INSERT INTO h_person(HPersonID,UserId,CreationDateTime,Gender,BirthDate,Race) 
  VALUES (1,'jd101','2002-12-14 09:11:00',1,'1983-08-23 08:15:10','American');

INSERT INTO h_person(HPersonID,UserId,CreationDateTime,Gender,BirthDate,Race) 
  VALUES (2,'lg22','2001-02-04 05:11:00',2,'1982-03-03 04:15:10','Asian');

---------------------------- INSERT INTO h_name---------------------------------------------------
INSERT INTO h_name(HNameID,UserId,CreationDateTime,FirstName,MiddleName,LastName,Active,HPersonID)
  VALUES(1,'lg22','2001-02-04 05:11:00','Louis','Ho','Guang',1,2);

INSERT INTO h_name(HNameID,UserId,CreationDateTime,FirstName,MiddleName,LastName,Active,HPersonID)
  VALUES(2,'jd101','2002-12-14 09:11:00','John','Jeff','Doe',1,1);

--------------------------- INSERT INTO h_patient ------------------------------------------------
INSERT INTO h_patient(HPatientID,UserId,CreationDateTime,MPINo,OrganDonor,DeceasedInd,IsPatientUnidentified,PrimaryLang,MedHistoryConcent,HPersonID)
  VALUES(1,'jd101','2002-12-14 09:11:00','M101','Richie',0,0,'English',0,1);

---------------------------- INSERT INTO h_staff--------------------------------------------------
-- 1:Physician 2:Nurse for Type
INSERT INTO h_staff(HStaffID,UserID,CreationDateTime,Type,Active) 
  VALUES(1,'lg22','2005-06-19 09:55:00',1,1);

---------------------------- INSERT INTO h_bed----------------------------------------------------
INSERT INTO h_bed(BedId,UserId,CreationDateTime,BedName,BedStatus,Active,LocationID)
  VALUES(1,'lg22','2004-03-18 12:55:00','Bed101',1,1,1);

--------------------------- INSERT INTO h_encounter ----------------------------------------------
INSERT INTO h_encounter(HEncounterID,UserId,CreationDateTime,EncStartDateTime,ENCEndDateTime,ENCStatus,EncLocationName
  ,EncounterLocation_ObjectID,EncounterID,EncType,BedName,Patient_ObjectID,AttendingPhysician_ObjectID,Bed_ObjectID)
  VALUES(1,'lg22','2006-02-14 19:55:00','2006-02-14 21:55:00','2006-02-14 22:55:00',1,'Exton',1,1,'Out Patient','Bed101',1,1,1);