--
-- Script was generated by Sushrut for EMRMS, Version 1.0.0.0
-- Script date 09/05/2017 21:52:44 PM
-- Server version: 5.7.19-log
--

-------------------------- INSERT INTO h_person--------------------------------------------------

INSERT INTO h_person(HPersonID,UserId,CreationDateTime,Gender,BirthDate,Race) 
  VALUES (1,'jd101','2002-12-14 09:11:00',1,'1983-08-23 08:15:10','American');

INSERT INTO h_person(HPersonID,UserId,CreationDateTime,Gender,BirthDate,Race) 
  VALUES (2,'lg22','2001-02-04 05:11:00',2,'1982-03-03 04:15:10','Asian');

---------------------------- INSERT INTO h_name---------------------------------------------------
INSERT INTO h_name(HNameID,UserId,CreationDateTime,FirstName,MiddleName,LastName,Active,HPersonID)
  VALUES(1,'lg22','2001-02-04 05:11:00','Louis','Ho','Guang',1,2);

INSERT INTO h_name(HNameID,UserId,CreationDateTime,FirstName,MiddleName,LastName,Active,HPersonID)
  VALUES(2,'jd101','2002-12-14 09:11:00','John','Jeff','Doe',1,1);

--------------------------- INSERT INTO h_patient ------------------------------------------------
INSERT INTO h_patient(HPatientID,UserId,CreationDateTime,MPINo,OrganDonor,DeceasedInd,IsPatientUnidentified,PrimaryLang,MedHistoryConcent,HPersonID)
  VALUES();


--------------------------- INSERT INTO h_encounter ----------------------------------------------
INSERT INTO h_encounter(HEncounterID,UserId,CreationDateTime,EncStartDateTime,ENCEndDateTime,ENCStatus,EncLocationName
  ,EncounterLocation_ObjectID,EncounterID,EncType,BedName,Patient_ObjectID,AttendingPhysician_ObjectID,Bed_ObjectID)
  VALUES()